### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by ganeshmajhi** [ganeshmajhi/tejam-Landing-Page#6]
Make the Footer of the Template responsive for mobile,tab and desktop using bootstrap or css3.

**Comment by prekshajagetiya123** [comment]
I would like to work on this

**Comment by ganeshmajhi** [comment]
Ok. Make It look Good For Mobile @prekshajagetiya123

**Comment by Shamsudeen12** [comment]
Can i become part of the team

**Comment by ganeshmajhi** [comment]
Yes , Make a Pull Request . :accept:

**Comment by BhathiyaTK** [comment]
Glad to work with this issue.
