### ISSUE TITLE
Add github page name in readme.md

### ISSUE THREAD

**Issue by ganeshmajhi** [ganeshmajhi/tejam-Landing-Page#7]
Add the page link in the readme.md  -( https://ganeshmajhi.github.io/tejam-Landing-Page/ ) with some description about the template.

**Comment by maarthi28** [comment]
I will take up this issue.

**Comment by ganeshmajhi** [comment]
Ok @maarthi28

**Comment by maarthi28** [comment]
@ganeshmajhi created pullrequest refer it.
